// Wording mirrors the Obsidian 1.13+ settings definitions.
export const descriptions: Record<string, string> = {
  "API base URL": "Where chat requests are sent.",
  "API key": "Saved only on this device.",
  "Model": "Choose a model or load the list from your provider.",
  "Reasoning effort": "Higher levels may be slower and cost more.",
  "Automatic detail notes": "How often the plugin writes a longer note for a paper. Only topics with Detail report turned on are considered. Manual “summarize paper” is unchanged.",
  "Timezone": "Which timezone defines the current day for reports and schedules.",
  "Daily reports folder": "Folder in this vault for daily report notes (relative path).",
  "Paper notes folder": "Folder in this vault for per-paper notes (relative path).",
  "Link style": "How links between notes are written in daily reports.",
  "Summary language": "Language for daily reports and paper notes.",
  "Run window": "Local times when automatic runs may start (24-hour clock).",
  "Check every (minutes)": "How often the plugin looks for a day that still needs a report. Default is 20 minutes.",
  "Library": "Choose a folder of PDFs, then build a search index. Separate from daily reports.",
  "Embedding API base URL": "OpenAI-compatible embeddings endpoint.",
  "Embedding API key": "Saved only on this device.",
  "Embedding model": "Model name sent to the endpoint.",
  "Embedding dimension": "Vector width of the remote model. Must match the model.",
  "Better PDF parser": "Optional local sidecar. Off by default; PDFs stay on this device either way.",
  "Sidecar capability URL": "Local loopback endpoint that reports parser capabilities.",
  "Sidecar parse URL": "Same-origin local loopback endpoint that accepts one PDF byte buffer.",
  "Verification code": "After you open the verification link, copy the long code shown on the web page (not the short code in the email link). Use the same email address as above.",
  "Resend API key": "From your Resend account. Saved only on this device; not shown again after you save.",
  "From email": "Optional. Leave blank for the simplest setup (mail may only go to your Resend account email). Use an address on a domain you verified in Resend to send more freely.",
  "From name": "Optional name shown as the sender. Default is \"arXiv Daily\".",
  "Log level": "How much detail appears in the developer console. Use debug only when troubleshooting; info is the default.",
  "Report a bug": "Opens a blank GitHub issue with the plugin version. A short description is enough.",
  "Request a feature": "Opens a blank GitHub issue. Write freely.",
  "Documentation": "Getting started guide on GitHub."
};
