import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { installHost } from '../src/host.mjs';
import { installedDsh } from './dsh-environment.mjs';
const dsh = installedDsh();
const capability = 'http://127.0.0.1:8123/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa/';
for (const order of ['gateway-first', 'plugin-first']) test(`real Connection keeps host and plugin working (${order})`, { skip: !dsh && 'DSH is required for transport compatibility' }, async t => {
  const require = createRequire(dsh.cli);
  const { Context } = await import(require.resolve('@deepseek-ai/cordis'));
  const { HostConnectionService } = await import(require.resolve('@deepseek-ai/dsh-client-connection'));
  const ctx = new Context(); t.after(() => ctx.fiber.dispose());
  const routes = new Map();
  ctx.provide('webServer', { port: 3080, register(route) { assert.equal(routes.has(route.path), false); routes.set(route.path, route); return () => routes.delete(route.path); } });
  const connection = new HostConnectionService(ctx, [], { isAuthenticated() { return true; } });
  const gateway = () => connection.rpc.intercept('/api', endpoint => endpoint === 'host/ping', async () => ({ ok: true, value: 'healthy' }));
  let disposed = 0;
  const manager = { async open() { return capability; }, async dispose() { disposed++; } };
  let stopGateway;
  if (order === 'gateway-first') stopGateway = gateway();
  let effect;
  installHost({ connection, webServer: { port: 3080 }, effect(fn) { effect = fn(); } }, manager);
  if (order === 'plugin-first') stopGateway = gateway();
  const shared = connection.createSharedFetchHandler('/api');
  const ping = () => shared.fetch(new Request('http://127.0.0.1:3080/api/host/ping', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ type: 'client-request', rpcId: 'host-check', method: 'host/ping', payload: {} }) })).then(r => r.json());
  assert.deepEqual((await ping()).result, { ok: true, value: 'healthy' });
  const opened = await shared.fetch(new Request('http://127.0.0.1:3080/api/arxiv-daily/open', { method: 'POST', body: JSON.stringify({ type: 'client-request', rpcId: 'open-check', method: 'arxiv-daily/open', payload: {} }) }));
  assert.deepEqual((await opened.json()).result, { ok: true, value: { url: capability } });
  await effect();
  assert.equal(disposed, 1); assert.equal((await shared.fetch(new Request('http://127.0.0.1:3080/api/arxiv-daily/open', { method: 'POST' }))).status, 404);
  assert.deepEqual((await ping()).result, { ok: true, value: 'healthy' }, 'plugin unload must leave the host gateway alone');
  await stopGateway();
});
