import { afterEach, expect, it, vi } from "vitest";
import { mkdtemp, rm, readFile } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { startWorkbench } from "../src/workbench/server";

const cleanup: Array<() => Promise<unknown>> = [];
afterEach(async () => { for (const close of cleanup.splice(0).reverse()) await close(); });
it("serves first-run setup and activates saved settings without restarting", async () => {
  const root = await mkdtemp(join(tmpdir(), "arxiv-onboard-"));
  cleanup.push(() => rm(root, { recursive: true, force: true }));
  const changed = vi.fn();
  let finish!: () => void;
  const run = vi.fn(async (_args, io, signal) => {
    io.stdout.write("secret-onboard-key");
    await new Promise<void>(resolve => { finish = resolve; signal.addEventListener("abort", () => resolve(), { once: true }); });
    return 0;
  });
  const app = await startWorkbench({ configPath: join(root, "config.toml"), onConfigSaved: changed, run, assets: { "index.html": { type: "text/html", body: "setup" } } });
  cleanup.push(app.close);
  const get = (route: string, body?: unknown) => fetch(new URL(route, app.url), body === undefined ? {} : { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
  expect(await (await get("")).text()).toBe("setup");
  expect(await (await get("api/status")).json()).toMatchObject({ setupRequired: true });
  expect((await get("api/runs", { kind: "daily" })).status).toBe(409);
  const initial = await (await get("api/settings")).json();
  expect(initial).toMatchObject({ setupRequired: true, revision: null });
  const values = { ...initial.values, vaultRoot: join(root, "vault"), baseUrl: "https://api.example.com/v1", provider: "custom", model: "test", apiKey: "secret-onboard-key", categories: ["cs.AI"], topics: [{ id: "test", name: "Models", tag: "models", description: "Efficient language models", detail: true }] };
  const saved = await get("api/settings", { revision: null, values });
  expect(saved.status).toBe(200);
  const text = await saved.text();
  expect(text).not.toContain("secret-onboard-key");
  expect(JSON.parse(text)).toMatchObject({ setupRequired: false });
  expect(changed).toHaveBeenCalledOnce();
  expect(await readFile(join(root, "config.toml"), "utf8")).toContain("secret-onboard-key");
  expect(await (await get("api/status")).json()).toMatchObject({ vaultRoot: values.vaultRoot });
  expect((await get("api/papers")).status).toBe(200);
  expect((await get("api/settings", { revision: null, values })).status).toBe(409);
  expect((await get("api/runs", { kind: "daily" })).status).toBe(202);
  await vi.waitFor(() => expect(run).toHaveBeenCalledOnce());
  const revision = JSON.parse(text).revision;
  expect((await get("api/settings", { revision, values })).status).toBe(409);
  expect(await (await get("api/runs/current")).text()).not.toContain("secret-onboard-key");
  finish();
  await vi.waitFor(async () => expect((await (await get("api/runs/current")).json()).run.status).toBe("completed"));
  const moved = { ...values, apiKey: "", vaultRoot: join(root, "other-vault") };
  expect((await get("api/settings", { revision, values: moved })).status).toBe(200);
  expect(await (await get("api/status")).json()).toMatchObject({ vaultRoot: moved.vaultRoot });
  expect((await get("api/settings", { revision, values })).status).toBe(409);
  const forbidden = await fetch(new URL("api/settings", app.url), { method: "POST", headers: { "Content-Type": "application/json", Origin: "https://attacker.invalid" }, body: JSON.stringify({ revision, values }) });
  expect(forbidden.status).toBe(403);
});
