import { afterEach, expect, it, vi } from "vitest";
import { mkdtemp, mkdir, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { startWorkbench } from "../src/workbench/server";
import { readWorkbenchSettings, saveWorkbenchSettings } from "../src/workbench/settings";
const cleanup: Array<() => Promise<unknown>> = [];
afterEach(async () => { for (const close of cleanup.splice(0).reverse()) await close(); });
it("binds settings actions to revisions and updates the active config after library mutations", async () => {
  const root = await mkdtemp(join(tmpdir(), "settings-actions-http-")); cleanup.push(() => rm(root, { recursive: true, force: true }));
  const configPath = join(root, "config.toml");
  const initial = await readWorkbenchSettings(configPath);
  const config = await saveWorkbenchSettings(configPath, { revision: null, values: { ...initial.values, vaultRoot: join(root, "vault"), apiKey: "test-secret" } });
  const folder = join(root, "papers"); await mkdir(folder);
  const updated = vi.fn();
  const app = await startWorkbench({ config, onConfigSaved: updated }); cleanup.push(app.close);
  const request = (route: string, body?: unknown) => fetch(new URL(route, app.url), body ? { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) } : {});
  expect((await request("api/settings/library")).status).toBe(200);
  expect((await request("api/settings/action", { revision: "stale", action: "library-connect", path: folder })).status).toBe(409);
  const connected = await request("api/settings/action", { revision: config.configRevision, action: "library-connect", path: folder });
  expect(connected.status).toBe(200);
  const snapshot = await connected.json();
  expect(snapshot.library.status.kind).not.toBe("disconnected");
  expect(snapshot.settings.revision).not.toBe(config.configRevision);
  expect(updated).toHaveBeenCalledOnce();
  const rejected = await request("api/settings/action", { revision: snapshot.settings.revision, action: "library-build" });
  expect(rejected.status).toBe(409);
  const invalid = await request("api/settings/action", { revision: snapshot.settings.revision, action: "execute-shell" });
  expect(invalid.status).toBe(400);
  const revoked = await request("api/settings/action", { revision: snapshot.settings.revision, action: "library-revoke" });
  expect(revoked.status).toBe(200);
});
